// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    la_porra
    (
        init => init
        upgrade => upgrade
        getOwner => owner
        getDeadline => deadline
        getTotalPot => total_pot
        getBetPrice => bet_price
        getWinningResult => winning_result
        isResolved => resolved
        getBets => get_bets
        getContractAddress => get_contract_address
        placeBet => place_bet
        resolveBets => resolve_bets
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
